Feature/transparency area
the-web-forest/Website pull request #47
Opened 2022-04-05 01:53 UTC by DevBacega

2022-04-05 01:54 UTC, Barros42 requested changes
Não subir variáveis de ambiente

2022-04-05 12:32 UTC, Barros42 requested changes

2022-04-05 12:32 UTC, Barros42 commented on components/ComboBox/index.tsx
> +        console.log('KCT', value);
Favor revisar e não subir palavrões

2022-04-05 12:32 UTC, Barros42 commented on pages/areaDeTransparencia.tsx
> +    if (firstLoad) {
```
    if (!firstLoad && !!selectedYear && !!selectedMonth) {
        return getDataTable();
    }   

    setFirstLoad(false);
```

Não seria o mesmo resultado sem aninhamento?

2022-04-05 12:32 UTC, Barros42 commented on pages/areaDeTransparencia.tsx
> +  }, [getDataTable, selectedMonth, selectedYear]);
Você esqueceu de adicionar a variável `firstLoad` aqui no array de dependências

2022-04-05 12:32 UTC, Barros42 commented on use-cases/GetAllYearsFromSheetListUseCase.ts
> +import ISelectOptionsEntity from '../core/entities/SelectOptionsEntity';
Importação não utilizada

2022-04-05 12:32 UTC, Barros42 commented on use-cases/GetAllYearsFromSheetListUseCase.ts
> +    const years = sheetList.map(sheet => sheet.title.split(/([\d])+/));
O que essa função faz exatamente?

2022-04-05 12:32 UTC, Barros42 commented on use-cases/GetAllYearsFromSheetListUseCase.ts
> +import MonthDto from '../pages/api/services/transparency/dtos/months.dto';
Erro nesse import

2022-04-05 12:32 UTC, Barros42 commented on core/const/Month.ts
>      days: 28,
Em casos de anos bissextos isso quebrará, favor utilizar funções JS para preencher a quantidade de dias.

```
 var dt = new Date();
 var month = dt.getMonth();
 var year = dt.getFullYear();
daysInMonth = new Date(year, month, 0).getDate();
```

2022-04-05 12:32 UTC, Barros42 commented on sections/TransparencyTable/index.tsx
> +import { useCallback } from 'react';
Importação não utilizada

2022-04-05 12:32 UTC, Barros42 commented on use-cases/GetSheetDataUseCase.ts
> +import YearDto from '../pages/api/services/transparency/dtos/year.dto';
Importação não utilizada

2022-04-08 02:00 UTC, DevBacega commented on pages/areaDeTransparencia.tsx
> +    if (firstLoad) {
Não esse é uma pratica para evitar renderização ao permanecer cache. Na primeira vez que ele renderizar ele desativa o first load, e assim não executa o getDataTable, e só quando as variáveis dentro do array de dependências modificar eu quero que ele execute.

2022-04-08 02:01 UTC, DevBacega commented on pages/areaDeTransparencia.tsx
> +  }, [getDataTable, selectedMonth, selectedYear]);
Foi proposital não colocar ela.

2022-04-08 02:09 UTC, Barros42 approved these changes

2022-04-08 02:09 UTC, merged